import { BetterRulesRecord } from '../betterRules';

const coreRules: BetterRulesRecord = {
  accessorPairs: [{ getWithoutSet: false, setWithoutGet: true, enforceForClassMembers: true }],
  arrayBracketNewline: false,
  arrayBracketSpacing: [ 'always',
    { singleValue: true, objectsInArrays: false, arraysInArrays: false }
  ],
  arrayCallbackReturn: [{ allowImplicit: true }],
  arrayElementNewline: false,
  arrowBodyStyle: [ 'as-needed', { requireReturnForObjectLiteral: false }],
  arrowParens: [ 'as-needed', { requireForBlockBody: false }],
  arrowSpacing: [{ before: true, after: true }],
  blockScopedVar: [],
  blockSpacing: [ 'always' ],
  callbackReturn: [[ 'callback', 'next' ]],
  capitalizedComments: [ 'always', {
    ignoreInlineComments: false, ignoreConsecutiveComments: true
  }],
  classMethodsUseThis: [{ exceptMethods: []}],
  commaDangle: [ 'never' ],
  commaStyle: [ 'last' ],
  complexity: false,
  computedPropertySpacing: [ 'never', { enforceForClassMembers: true }],
  consistentReturn: false,
  consistentThis: [ 'that' ],
  constructorSuper: [],
  curly: [ 'all' ],
  defaultCase: [],
  defaultCaseLast: [],
  dotLocation: [ 'object' ],
  eolLast: [ 'always' ],
  eqeqeq: [ 'always' ],
  forDirection: [],
  funcNameMatching: false,
  funcNames: false,
  funcStyle: [ 'expression' ],
  functionCallArgumentNewline: [ 'consistent' ],
  functionParenNewline: [ 'consistent' ],
  generatorStarSpacing: [{ before: true, after: true }],
  getterReturn: [{ allowImplicit: true }],
  globalRequire: [],
  groupedAccessorPairs: [ 'getBeforeSet' ],
  guardForIn: [],
  // eslint-disable-next-line extended/consistent-err-names
  handleCallbackErr: [ 'err' ],
  idDenylist: false,
  idLength: [{
    min: 2,
    max: Number.POSITIVE_INFINITY,
    properties: 'always',
    exceptions: [ '_', 'i', 'j', 't', 'x', 'y', 'z' ]
  }],
  idMatch: false,
  implicitArrowLinebreak: false,
  initDeclarations: false,
  jsxQuotes: [ 'prefer-single' ],
  keySpacing: [{ beforeColon: false, afterColon: true, mode: 'strict' }],
  linebreakStyle: [ 'unix' ],
  lineCommentPosition: [{ position: 'above' }],
  linesAroundComment: [{
    beforeBlockComment: false,
    afterBlockComment: false,
    beforeLineComment: true,
    afterLineComment: false,
    allowBlockStart: true,
    allowBlockEnd: true,
    allowObjectStart: true,
    allowObjectEnd: true,
    allowArrayStart: true,
    allowArrayEnd: true,
    allowClassStart: true,
    allowClassEnd: true,
    applyDefaultIgnorePatterns: true
  }],
  maxClassesPerFile: false,
  maxDepth: false,
  maxLen: false,
  maxLines: false,
  maxLinesPerFunction: false,
  maxNestedCallbacks: false,
  maxParams: false,
  maxStatements: false,
  maxStatementsPerLine: [{ max: 1 }],
  multilineCommentStyle: [ 'separate-lines' ],
  multilineTernary: [ 'always-multiline' ],
  newCap: [{
    newIsCap: true,
    capIsNew: true,
    newIsCapExceptions: [],
    capIsNewExceptions: [],
    properties: true
  }],
  newlinePerChainedCall: [{ ignoreChainWithDepth: 4 }],
  newParens: [ 'always' ],
  noAlert: [],
  noAsyncPromiseExecutor: false,
  noAwaitInLoop: false,
  noBitwise: [{ allow: [], int32Hint: false }],
  noBufferConstructor: [],
  noCaller: [],
  noCaseDeclarations: [],
  noClassAssign: [],
  noCompareNegZero: [],
  noCondAssign: [ 'always' ],
  noConfusingArrow: false,
  noConsole: [],
  noConstantCondition: [{ checkLoops: true }],
  noConstAssign: [],
  noConstructorReturn: [],
  noContinue: false,
  noControlRegex: [],
  noDebugger: [],
  noDeleteVar: [],
  noDivRegex: [],
  noDupeArgs: [],
  noDupeElseIf: [],
  noDupeKeys: [],
  noDuplicateCase: [],
  noDuplicateImports: [{ includeExports: true }],
  noElseReturn: [{ allowElseIf: false }],
  noEmpty: [{ allowEmptyCatch: false }],
  noEmptyCharacterClass: [],
  noEmptyPattern: [],
  noEqNull: [],
  noEval: [{ allowIndirect: false }],
  noExAssign: [],
  noExtendNative: [{ exceptions: []}],
  noExtraBind: [],
  noExtraBooleanCast: [],
  noExtraLabel: [],
  noFallthrough: [],
  noFloatingDecimal: [],
  noFuncAssign: [],
  noGlobalAssign: [{ exceptions: []}],
  noImplicitCoercion: [],
  noImplicitGlobals: [{ lexicalBindings: false }],
  noImpliedEval: [],
  noImportAssign: [],
  noInlineComments: [],
  noInnerDeclarations: [ 'both' ],
  noInvalidRegexp: [{ allowConstructorFlags: [ 'u', 'y' ]}],
  noInvalidThis: false,
  noIrregularWhitespace: [{
    skipComments: false,
    skipRegExps: false,
    skipStrings: false,
    skipTemplates: false
  }],
  noIterator: [],
  noLabels: [{ allowLoop: false, allowSwitch: false }],
  noLabelVar: [],
  noLoneBlocks: [],
  noLonelyIf: [],
  noMisleadingCharacterClass: [],
  noMixedOperators: [],
  noMixedRequires: [{ grouping: true, allowCall: false }],
  noMixedSpacesAndTabs: [],
  noMultiAssign: [],
  // eslint-disable-next-line @typescript-eslint/naming-convention
  noMultipleEmptyLines: [{ max: 1, maxEOF: 1, maxBOF: 0 }],
  noMultiSpaces: [{
    // eslint-disable-next-line @typescript-eslint/naming-convention
    ignoreEOLComments: false,
    exceptions: {
      BinaryExpression: false,
      ImportDeclaration: false,
      Property: false,
      VariableDeclarator: false
    }
  }],
  noMultiStr: [],
  nonblockStatementBodyPosition: [ 'below' ],
  noNegatedCondition: false,

  // The noNestedTernary rule is superseded by the unicorn/noNestedTernary
  // rule.
  noNestedTernary: false,
  noNew: [],
  noNewFunc: [],
  noNewObject: [],
  noNewRequire: [],
  noNewSymbol: [],
  noNewWrappers: [],
  noNonoctalDecimalEscape: [],
  noObjCalls: [],
  noOctal: [],
  noOctalEscape: [],
  noParamReassign: [{ props: true, ignorePropertyModificationsFor: []}],
  noPathConcat: [],
  noPlusplus: [{ allowForLoopAfterthoughts: true }],
  noProcessEnv: [],

  // The noProcessExit rule is superseded by the unicorn/noProcessExit rule.
  noProcessExit: false,
  noPromiseExecutorReturn: false,
  noProto: [],
  noPrototypeBuiltins: [],
  noRedeclare: [{ builtinGlobals: true }],
  noRegexSpaces: [],
  noRestrictedExports: false,
  noRestrictedGlobals: [],
  noRestrictedImports: false,
  noRestrictedModules: false,
  noRestrictedProperties: false,
  noRestrictedSyntax: false,
  noReturnAssign: [ 'always' ],
  noReturnAwait: false,
  noScriptUrl: [],
  noSelfAssign: [{ props: true }],
  noSelfCompare: [],
  noSequences: [],
  noSetterReturn: [],
  noShadowRestrictedNames: [],
  noSparseArrays: [],
  noSync: [{ allowAtRootLevel: false }],
  noTabs: [{ allowIndentationTabs: false }],
  noTemplateCurlyInString: [],
  noTernary: false,
  noThisBeforeSuper: [],
  noThrowLiteral: [],
  noTrailingSpaces: [{ ignoreComments: false, skipBlankLines: false }],
  noUndef: [{ typeof: true }],
  noUndefined: false,
  noUndefInit: [],
  noUnderscoreDangle: [{
    allow: [ '__html' ],
    allowAfterThis: false,
    allowAfterThisConstructor: false,
    allowAfterSuper: false,
    allowFunctionParams: false,
    enforceInMethodNames: true
  }],
  noUnexpectedMultiline: [],
  noUnmodifiedLoopCondition: [],
  noUnneededTernary: [{ defaultAssignment: false }],
  noUnreachable: [],
  noUnreachableLoop: [],
  noUnsafeFinally: [],
  noUnsafeNegation: [],
  noUnsafeOptionalChaining: [{ disallowArithmeticOperators: true }],
  noUnusedExpressions: [{
    allowShortCircuit: false,
    allowTernary: false,
    allowTaggedTemplates: false
  }],
  noUnusedLabels: [],
  noUselessBackreference: [],
  noUselessCall: [],
  noUselessCatch: [],
  noUselessComputedKey: [{ enforceForClassMembers: true }],
  noUselessConcat: [],
  noUselessEscape: [],
  noUselessRename: [{
    ignoreDestructuring: false,
    ignoreImport: false,
    ignoreExport: false
  }],
  noUselessReturn: [],
  noVar: [],
  noVoid: [],
  noWarningComments: false,
  noWhitespaceBeforeProperty: [],
  noWith: [],
  objectCurlyNewline: [{
    ObjectExpression: { consistent: true },
    ObjectPattern: { consistent: true },
    ImportDeclaration: { consistent: true },
    ExportDeclaration: { consistent: true }
  }],
  objectCurlySpacing: [ 'always', { objectsInObjects: false, arraysInObjects: false }],
  objectPropertyNewline: [{ allowAllPropertiesOnSameLine: true }],
  objectShorthand: [ 'always', { avoidQuotes: false, ignoreConstructors: false, avoidExplicitReturnArrows: true }],
  oneVar: false,
  oneVarDeclarationPerLine: [ 'always' ],
  operatorAssignment: [ 'always' ],
  operatorLinebreak: [ 'after' ],
  paddedBlocks: [ 'never', { allowSingleLineBlocks: true }],
  paddingLineBetweenStatements: [
    { blankLine: 'always', prev: '*', next: 'return' },
    { blankLine: 'always', prev: [ 'const', 'let', 'var' ], next: '*' },
    { blankLine: 'any', prev: [ 'const', 'let', 'var' ], next: [ 'const', 'let', 'var' ]},
    { blankLine: 'always', prev: 'directive', next: '*' },
    { blankLine: 'any', prev: 'directive', next: 'directive' }
  ],
  preferArrowCallback: [{
    allowNamedFunctions: false,
    allowUnboundThis: true
  }],
  preferConst: [{
    destructuring: 'any',
    ignoreReadBeforeAssign: true
  }],

  // Arrays are disabled here because of the unicorn/noUnreadableArrayDestructuring
  // rule.
  preferDestructuring: [
    { array: false, object: true },
    { enforceForRenamedProperties: false }
  ],
  preferExponentiationOperator: [],
  preferNamedCaptureGroup: [],
  preferNumericLiterals: [],
  preferObjectSpread: [],
  preferPromiseRejectErrors: [{ allowEmptyReject: false }],
  preferRegexLiterals: [],
  preferRestParams: [],
  preferSpread: [],
  preferTemplate: [],
  quoteProps: [ 'as-needed', {
    keywords: false, unnecessary: true, numbers: false
  }],
  quotes: [ 'single', { avoidEscape: false, allowTemplateLiterals: true }],
  radix: [ 'always' ],
  requireAtomicUpdates: false,
  requireUnicodeRegexp: [],
  requireYield: [],
  restSpreadSpacing: [ 'never' ],
  semiSpacing: [{ before: false, after: true }],
  semiStyle: [ 'last' ],
  sortImports: [{
    ignoreCase: true,
    ignoreDeclarationSort: false,
    ignoreMemberSort: false,
    memberSyntaxSortOrder: [
      'single',
      'multiple',
      'all',
      'none'
    ]
  }],
  sortKeys: false,
  sortVars: [{ ignoreCase: true }],
  spaceBeforeBlocks: [ 'always' ],
  spacedComment: [ 'always', { exceptions: [], markers: []}],
  spaceInParens: [ 'never' ],
  spaceUnaryOps: [{ words: true, nonwords: false }],
  strict: [ 'global' ],
  switchColonSpacing: [{ after: true, before: false }],
  symbolDescription: [],
  templateCurlySpacing: [ 'never' ],
  templateTagSpacing: [ 'never' ],
  unicodeBom: [ 'never' ],
  useIsnan: [{ enforceForSwitchCase: true }],
  validTypeof: [{ requireStringLiterals: true }],
  varsOnTop: [],
  wrapIife: [ 'inside', { functionPrototypeMethods: true }],
  wrapRegex: false,
  yieldStarSpacing: [{ before: true, after: true }],
  yoda: [ 'never', {
    exceptRange: true, onlyEquality: false
  }]
};

export {
  coreRules
};
