'use strict';

module.exports = {
  'plugins': [
    'mocha'
  ],

  'env': {
    'amd': false,
    'browser': true,
    'es6': false,
    'jasmine': false,
    'jquery': false,
    'meteor': false,
    'mocha': true,
    'node': true,
    'phantomjs': false,
    'prototypejs': false,
    'shelljs': false
  },

  'globals': {
    'angular': false
  },

  'ecmaFeatures': {
    'arrowFunctions': false,
    'binaryLiterals': false,
    'blockBindings': false,
    'classes': false,
    'defaultParams': false,
    'destructuring': false,
    'forOf': false,
    'generators': false,
    'globalReturn': false,
    'jsx': false,
    'modules': false,
    'objectLiteralComputedProperties': false,
    'objectLiteralDuplicateProperties': false,
    'objectLiteralShorthandMethods': false,
    'objectLiteralShorthandProperties': false,
    'octalLiterals': false,
    'regexUFlag': false,
    'regexYFlag': false,
    'restParams': false,
    'spread': false,
    'superInFunctions': false,
    'templateStrings': false,
    'unicodeCodePointEscapes': false
  },

  'rules': {
    'comma-dangle': [ 2, 'never' ],
    'no-cond-assign': [ 2, 'always' ],
    'no-console': 2,
    'no-constant-condition': 2,
    'no-control-regex': 2,
    'no-debugger': 2,
    'no-dupe-args': 2,
    'no-dupe-keys': 2,
    'no-duplicate-case': 2,
    'no-empty': 2,
    'no-empty-class': 2,
    'no-ex-assign': 2,
    'no-extra-boolean-cast': 2,
    'no-extra-parens': 0,
    'no-extra-semi': 2,
    'no-func-assign': 2,
    'no-inner-declarations': [ 2, 'both' ],
    'no-invalid-regexp': 2,
    'no-irregular-whitespace': 2,
    'no-negated-in-lhs': 2,
    'no-obj-calls': 2,
    'no-regex-spaces': 2,
    'no-reserved-keys': 0,
    'no-sparse-arrays': 2,
    'no-unreachable': 2,
    'use-isnan': 2,
    'valid-jsdoc': 0,
    'valid-typeof': 2,

    'block-scoped-var': 2,
    'complexity': [ 0, 11 ],
    'consistent-return': 2,
    'curly': [ 2, 'all' ],
    'default-case': 2,
    'dot-location': [ 2, 'object' ],
    'dot-notation': [ 2, { 'allowKeywords': true } ],
    'eqeqeq': 2,
    'guard-for-in': 2,
    'no-alert': 2,
    'no-caller': 2,
    'no-div-regex': 2,
    'no-else-return': 2,
    'no-empty-label': 2,
    'no-eq-null': 2,
    'no-eval': 2,
    'no-extend-native': 2,
    'no-extra-bind': 2,
    'no-fallthrough': 2,
    'no-floating-decimal': 2,
    'no-implied-eval': 2,
    'no-iterator': 2,
    'no-labels': 2,
    'no-lone-blocks': 2,
    'no-loop-func': 2,
    'no-multi-spaces': 2,
    'no-multi-str': 2,
    'no-native-reassign': 2,
    'no-new': 2,
    'no-new-func': 2,
    'no-new-wrappers': 2,
    'no-octal': 2,
    'no-octal-escape': 2,
    'no-param-reassign': 0,
    'no-process-env': 2,
    'no-proto': 2,
    'no-redeclare': 2,
    'no-return-assign': 2,
    'no-script-url': 2,
    'no-self-compare': 2,
    'no-sequences': 2,
    'no-throw-literal': 2,
    'no-unused-expressions': 2,
    'no-void': 2,
    'no-warning-comments': 2,
    'no-with': 2,
    'radix': 2,
    'vars-on-top': 2,
    'wrap-iife': [ 2, 'inside' ],
    'yoda': [ 2, 'never' ],

    'strict': [ 2, 'global' ],

    'no-catch-shadow': 2,
    'no-delete-var': 2,
    'no-label-var': 2,
    'no-shadow': 2,
    'no-shadow-restricted-names': 2,
    'no-undef': 2,
    'no-undef-init': 2,
    'no-undefined': 0,
    'no-unused-vars': [ 2, { 'vars': 'all', 'args': 'after-used' } ],
    'no-use-before-define': 2,

    'handle-callback-err': [ 2, 'err' ],
    'no-mixed-requires': [ 2, true ],
    'no-new-require': 2,
    'no-path-concat': 2,
    'no-process-exit': 2,
    'no-restricted-modules': 0,
    'no-sync': 0,

    'brace-style': [ 2, '1tbs', { 'allowSingleLine': false } ],
    'camelcase': 2,
    'comma-spacing': [ 2, { 'before': false, 'after': true } ],
    'comma-style': [ 2, 'last' ],
    'computed-property-spacing': [2, 'never'],
    'consistent-this': [ 2, 'that' ],
    'eol-last': 2,
    'func-names': 0,
    'func-style': [ 2, 'expression' ],
    'indent': [2, 2, { 'indentSwitchCase': true }],
    'key-spacing': [ 2, { 'beforeColon': false, 'afterColon': true } ],
    'linebreak-style': [ 2, 'unix' ],
    'max-nested-callbacks': [ 0, 3 ],
    'new-cap': [ 2, { 'newIsCap': true, 'capIsNew': true } ],
    'new-parens': 2,
    'newline-after-var': [ 2, 'always' ],
    'no-array-constructor': 2,
    'no-continue': 0,
    'no-inline-comments': 2,
    'no-lonely-if': 2,
    'no-mixed-spaces-and-tabs': [ 2 ],
    'no-multiple-empty-lines': [ 2, { 'max': 1 } ],
    'no-nested-ternary': 2,
    'no-new-object': 2,
    'no-spaced-func': 2,
    'no-ternary': 0,
    'no-trailing-spaces': [ 2, { 'skipBlankLines': false } ],
    'no-underscore-dangle': 2,
    'no-unneeded-ternary': 2,
    'no-wrap-func': 2,
    'one-var': 0,
    'operator-assignment': [ 2, 'always' ],
    'operator-linebreak': [ 2, 'after' ],
    'padded-blocks': [ 2, 'never' ],
    'quote-props': [ 2, 'as-needed' ],
    'quotes': [ 2, 'single' ],
    'semi': [ 2, 'always' ],
    'semi-spacing': [ 2, { 'before': false, 'after': true } ],
    'sort-vars': [ 2, { 'ignoreCase': true } ],
    'space-after-keywords': [ 2, 'always' ],
    'space-before-blocks': [ 2, 'always' ],
    'space-before-function-paren': [ 2, { 'anonymous': 'always', 'named': 'always' } ],
    'space-in-brackets': [ 2, 'always', { 'singleValue': true, 'objectsInArrays': false, 'arraysInArrays': false, 'arraysInObjects': false, 'objectsInObjects': false, 'propertyName': false } ],
    'space-in-parens': [ 2, 'never' ],
    'space-infix-ops': [ 2, { 'int32Hint': false } ],
    'space-return-throw-case': 2,
    'space-unary-ops': [ 2, { 'words': true, 'nonwords': false } ],
    'spaced-comment': [ 2, 'always' ],
    'wrap-regex': 0,

    'generator-star-spacing': [ 2, 'both' ],
    'no-var': 0,
    'object-shorthand': [ 2, 'never' ],
    'prefer-const': 0,

    'max-depth': [ 0, 4 ],
    'max-len': [ 0, 80, 4 ],
    'max-params': [ 0, 3 ],
    'max-statements': [ 0, 10 ],
    'no-bitwise': 0,
    'no-plusplus': 0,

    'mocha/no-exclusive-tests': 2
  }
};
