name: Release

on:
  push:
    branches:
      - 'master'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: |
        npm install
    - name: Build
      run: |
        npx roboter build
    - name: Run roboter
      run: |
        npx roboter
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN_ADMIN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN_ADMIN }}
      # Build again as `npx roboter` cleans the build directory
      run: |
        npx roboter build
        npx semantic-release
